/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#000000',
        'primary-container': '#131b2e',
        'on-primary': '#ffffff',
        'on-primary-container': '#7c839b',
        'secondary': '#0058be',
        'secondary-container': '#2170e4',
        'on-secondary-container': '#fefcff',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#001a42',
        'on-secondary-fixed-variant': '#004395',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc6ff',
        'background': '#f8f9ff',
        'on-background': '#0b1c30',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#45464d',
        'surface': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-tint': '#565e74',
        'surface-variant': '#d3e4fe',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'outline': '#76777d',
        'outline-variant': '#c6c6cd',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#bec6e0',
        'tertiary': '#000000',
        'tertiary-container': '#191c1e',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#818486',
        'tertiary-fixed': '#e0e3e5',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-tertiary-fixed': '#191c1e',
        'on-tertiary-fixed-variant': '#444749',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
      },
      borderRadius: {
        none: '0px',
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'utility-panel-width': '320px',
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'stack-lg': '1.5rem',
        'gutter': '1.5rem',
        'sidebar-width': '260px',
      },
      fontFamily: {
        'display-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-md': ['"Hanken Grotesk"', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'title-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'title-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
