apiVersion: v1
kind: Namespace
metadata:
  name: ivaisoft
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: chat-flow-machine-secrets
  namespace: ivaisoft
spec:
  organizationId: 476cd137-bd26-44b6-ab15-b43001160841
  secretName: chat-flow-machine-secrets
  onlyMappedSecrets: true
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: cc146430-dc23-4d7c-b740-b4be00dc306f
      secretKeyName: API_MACHINE_SECRET
    - bwSecretId: a60e2396-b823-4415-ac54-b4be00dc3128
      secretKeyName: N8N_MACHINE_SECRET
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: chat-flow-secrets
  namespace: ivaisoft
spec:
  organizationId: 476cd137-bd26-44b6-ab15-b43001160841
  secretName: chat-flow-secrets
  onlyMappedSecrets: true
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: 3fe73214-82e4-457f-9285-b4be00f25186
      secretKeyName: SUPABASE_SERVICE_ROLE_KEY
